# Generated by Django 3.0.2 on 2020-03-16 14:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200316_1958'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
    ]
