# Generated by Django 3.0.2 on 2020-03-16 14:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200316_2021'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('c', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('p', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('t', django.db.models.manager.Manager()),
            ],
        ),
    ]
